services:
  backend:
    stop_grace_period: 0s
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src
      - ./backend/countries.sqlite:/app/countries.sqlite
  frontend:
    stop_grace_period: 0s
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
    environment:
      - API_URL=http://backend:4000/graphql
